# Generated by Django 5.0.7 on 2024-08-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_postlikes_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestedcommentlike',
            name='nested_comment',
        ),
        migrations.RemoveField(
            model_name='nestedcommentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='NestedComment',
        ),
        migrations.DeleteModel(
            name='NestedCommentLike',
        ),
    ]
