# Generated by Django 5.0.7 on 2024-08-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_nestedcommentlike_nested_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='counter',
            field=models.IntegerField(null=True),
        ),
    ]
