# Generated by Django 5.0.7 on 2024-08-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_dummys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
