# Generated by Django 5.0.7 on 2024-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_role_userrole_userrolelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('non-admin', 'Non-Admin')], max_length=20),
        ),
    ]
