# Generated by Django 5.0.7 on 2024-08-05 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email address must be from gmail, yahoo, or myyahoo domains and end with .com or .in.', regex='^[a-zA-Z][\\w._]+@(gmail|yahoo|myyahoo)\\.(com|in)$')]),
        ),
    ]
